### ISSUE TITLE
Peek Solution not appearing after restarting  Understanding Ownership / The Slice Type / Trim a String

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/rustlings-course#235] opened 2023-04-11 15:08 UTC
I started the Learn Rust course and Peek Solution was available, but after restarting jetbrains-idea-ce the Peek Solution link no longer brought anything up.  I reset the Learn Rust course in My Courses and it worked again until another restart.   (using Fedora)  
No error message showing.  The "Peek Solution..." link simply doesn't do anything when clicked.

**Comment by DanielMcCord** [comment] 2023-09-01 05:01
@sofiiako This issue appears when using JetBrains Academy plugin version 2022.7 or later. See the [changelog for 2022.7](https://youtrack.jetbrains.com/issues?q=project%3A+%7BJetbrains+Academy%7D+Fix+versions%3A+2022.7) to narrow it down further. Other courses such as C++ Basics are not affected by this issue. Also, I reproduced this in CLion, so it isn't specific to IntelliJ IDEA Community Edition.

**Reproduction steps:**
1. Start the Learn Rust course using JetBrains Academy (aka EduTools) 2022.7 or later.
2.  Restart the IDE.
3. Attempt to use "Peek Solution..." on any task(s) in the course. Nothing happens.

Note: it is possible to avoid this bug by starting the course using an older version of EduTools. Once the course has been started, updating the plugin does not trigger the bug. See below.

**Workaround - use at your own risk:**
1. Install a 2022.1.* IDE.
4. Download EduTools 2022.6-2022.1-569 from [here](https://plugins.jetbrains.com/plugin/10081-jetbrains-academy/versions/stable)
5. Manually install the downloaded plugin.
6. Close and reopen the IDE.
7. Start the course.
8. Install the update for the plugin, but do not click "restart" yet.
9. Wait for any background tasks from step 5 to finish. 
10. Restart the IDE.

**Comment by kochaika** [comment] 2023-11-15 10:56
Seems to be fixed in #284

**Closed by kochaika** 2023-11-15 10:56 UTC
Labels: bug
